services:
  seatofpants:
    image: ghcr.io/casterlabs/seatofpants:latest
    restart: always
    # network_mode: host # Required for the docker provider.
    volumes:
      - data:/home/container/data
      # - /var/run/docker.sock:/var/run/docker.sock # Only needed if you use the Docker provider
    ports: # Comment this block if you use the docker provider.
      - 9000:10246 # Change 9000 to your liking.

volumes:
  data: